In [23]:
import pandas as pd

In [24]:
df = pd.read_excel(r"C:\Users\nuhai\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [25]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [26]:
df = df.drop(columns = "Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [28]:
df["Last_Name"] = df["Last_Name"].str.lstrip("...")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [30]:
df["Last_Name"] = df["Last_Name"].str.lstrip("/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [81]:
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','',regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [86]:
df["Phone_Number"].apply(lambda x: str(x))

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18
19    8766783469
Name: Phone_Number, dtype: object

In [87]:
df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8               --
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18              --
19    876-678-3469
Name: Phone_Number, dtype: object

In [88]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [91]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [93]:
df["Phone_Number"] = df["Phone_Number"].str.replace('--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [98]:
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',', n=2,  expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [99]:
df = df.drop(columns = "Address")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [102]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [103]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')

df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [107]:
df = df.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [108]:
df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [109]:
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [110]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [111]:
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [112]:
df = df.drop(columns = "Zip_Code")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine